// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBda6BpfhuFXUTnRWSonPhUADumrluWEhA',
    appId: '1:594594272443:web:0d90cbfde1d105aa09059e',
    messagingSenderId: '594594272443',
    projectId: 'cocial-media-1bbf2',
    authDomain: 'cocial-media-1bbf2.firebaseapp.com',
    storageBucket: 'cocial-media-1bbf2.firebasestorage.app',
    measurementId: 'G-LL6K7QWEXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYU_iSGhhjzOJyNRMmOoRl3_KrG51EJkA',
    appId: '1:594594272443:android:8704b7f26bbb42ab09059e',
    messagingSenderId: '594594272443',
    projectId: 'cocial-media-1bbf2',
    storageBucket: 'cocial-media-1bbf2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCau8FcgaoHGFIHIAb8CYRIoEIh8K7bWL0',
    appId: '1:594594272443:ios:796d7c994be3293209059e',
    messagingSenderId: '594594272443',
    projectId: 'cocial-media-1bbf2',
    storageBucket: 'cocial-media-1bbf2.firebasestorage.app',
    iosBundleId: 'com.example.socialMedia',
  );
}
